# Generated by Django 5.2.4 on 2026-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_gramos', models.FloatField()),
                ('proveedor', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jabon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('LAV', 'Lavandería y Hogar'), ('CP', 'Cuidado Personal y Piel')], default='CP', max_length=3)),
                ('fecha_elaboracion', models.DateField()),
                ('peso_gramos', models.FloatField()),
            ],
        ),
    ]
