# Generated by Django 5.2.4 on 2026-04-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_consumoinsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaJabon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.IntegerField()),
                ('motivo_salida', models.CharField(choices=[('VENTA', 'Venta'), ('REGALO', 'Regalo'), ('USO', 'Uso Personal'), ('MERMA', 'Merma/Daño')], default='VENTA', max_length=10)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('jabon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='inventory.jabon')),
            ],
        ),
    ]
