# Generated by Django 5.2.4 on 2026-04-24 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salidajabon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTANDAR', 'Receta Estándar'), ('EXPERIMENTO', 'Experimento/Nuevo')], max_length=20)),
                ('fecha_elaboracion', models.DateTimeField(auto_now_add=True)),
                ('unidades_resultantes', models.IntegerField(default=0)),
                ('temperatura_mezcla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProduccionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_origen', models.CharField(help_text='ID del lote de materia prima', max_length=50)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario_momento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.insumos')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumos', to='inventory.produccion')),
            ],
        ),
        migrations.AddField(
            model_name='produccion',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.receta'),
        ),
    ]
