# Generated by Django 5.2.4 on 2026-04-26 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_produccion_receta_detalleproduccioninsumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='jabon_producido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='inventory.jabon'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_gramos',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
