# Generated by Django 5.2.4 on 2026-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_produccion_jabon_producido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produccion',
            name='en_curado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_termino_curado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
