# Generated by Django 5.2.4 on 2026-06-16 02:01

import django.db.models.deletion
from django.db import migrations, models

def crear_y_mapear_categorias(apps, schema_editor):
    Categoria = apps.get_model('inventory', 'Categoria')
    Jabon = apps.get_model('inventory', 'Jabon')

    # Crear las categorías por defecto
    cp, _ = Categoria.objects.get_or_create(nombre="Cuidado Personal")
    lav, _ = Categoria.objects.get_or_create(nombre="Lavandería")

    # Mapear los valores de texto viejos a las claves primarias de los nuevos registros
    for jabon in Jabon.objects.all():
        if jabon.categoria == 'CP':
            jabon.categoria = str(cp.id)
            jabon.save()
        elif jabon.categoria == 'LAV':
            jabon.categoria = str(lav.id)
            jabon.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_produccion_completada_produccion_en_curado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_peso', models.CharField(default='g', max_length=10)),
                ('dias_curado_defecto', models.IntegerField(default=28)),
                ('umbral_critico_stock', models.IntegerField(default=5)),
            ],
        ),
        # Ejecutar la migración de datos antes de cambiar el tipo de columna a ForeignKey
        migrations.RunPython(crear_y_mapear_categorias),
        migrations.AlterField(
            model_name='jabon',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jabones', to='inventory.categoria'),
        ),
    ]
