# Generated by Django 5.2.4 on 2026-06-16 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_categoria_configuracionsistema_alter_jabon_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabon',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jabones', to='inventory.categoria'),
        ),
    ]
