# Generated by Django 5.2.4 on 2026-06-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_jabon_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='receta',
            name='cantidad_piezas_base',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='receta',
            name='jabon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='inventory.jabon'),
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.FloatField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.insumos')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventory.receta')),
            ],
        ),
    ]
