# Generated by Django 5.2.4 on 2026-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_receta_descripcion_remove_receta_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
