# Generated by Django 5.2.4 on 2026-06-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_insumos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidajabon',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
