# Generated by Django 5.2.4 on 2026-07-27 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_recuperacionclave'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='umbral_advertencia',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='insumos',
            name='umbral_critico',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
